/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnomaliesRouteImport } from './routes/anomalies'
import { Route as AssetsRouteImport } from './routes/assets'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CollaborationRouteImport } from './routes/collaboration'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as CopilotRouteImport } from './routes/copilot'
import { Route as DigitalTwinRouteImport } from './routes/digital-twin'
import { Route as ExecutiveRouteImport } from './routes/executive'
import { Route as GlobeRouteImport } from './routes/globe'
import { Route as IncidentResponseRouteImport } from './routes/incident-response'
import { Route as IncidentsRouteImport } from './routes/incidents'
import { Route as InvestigationRouteImport } from './routes/investigation'
import { Route as MitreRouteImport } from './routes/mitre'
import { Route as NetworkRouteImport } from './routes/network'
import { Route as ReportGenRouteImport } from './routes/report-gen'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SimulationRouteImport } from './routes/simulation'
import { Route as SocRouteImport } from './routes/soc'
import { Route as ThreatIntelRouteImport } from './routes/threat-intel'
import { Route as ThreatIntelligenceAiRouteImport } from './routes/threat-intelligence-ai'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as VulnerabilitiesRouteImport } from './routes/vulnerabilities'
import { Route as AuthForgotRouteImport } from './routes/auth.forgot'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthRegisterRouteImport } from './routes/auth.register'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnomaliesRoute = AnomaliesRouteImport.update({
  id: '/anomalies',
  path: '/anomalies',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsRoute = AssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CollaborationRoute = CollaborationRouteImport.update({
  id: '/collaboration',
  path: '/collaboration',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const CopilotRoute = CopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => rootRouteImport,
} as any)
const DigitalTwinRoute = DigitalTwinRouteImport.update({
  id: '/digital-twin',
  path: '/digital-twin',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecutiveRoute = ExecutiveRouteImport.update({
  id: '/executive',
  path: '/executive',
  getParentRoute: () => rootRouteImport,
} as any)
const GlobeRoute = GlobeRouteImport.update({
  id: '/globe',
  path: '/globe',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentResponseRoute = IncidentResponseRouteImport.update({
  id: '/incident-response',
  path: '/incident-response',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsRoute = IncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestigationRoute = InvestigationRouteImport.update({
  id: '/investigation',
  path: '/investigation',
  getParentRoute: () => rootRouteImport,
} as any)
const MitreRoute = MitreRouteImport.update({
  id: '/mitre',
  path: '/mitre',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkRoute = NetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportGenRoute = ReportGenRouteImport.update({
  id: '/report-gen',
  path: '/report-gen',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulationRoute = SimulationRouteImport.update({
  id: '/simulation',
  path: '/simulation',
  getParentRoute: () => rootRouteImport,
} as any)
const SocRoute = SocRouteImport.update({
  id: '/soc',
  path: '/soc',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreatIntelRoute = ThreatIntelRouteImport.update({
  id: '/threat-intel',
  path: '/threat-intel',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreatIntelligenceAiRoute = ThreatIntelligenceAiRouteImport.update({
  id: '/threat-intelligence-ai',
  path: '/threat-intelligence-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const VulnerabilitiesRoute = VulnerabilitiesRouteImport.update({
  id: '/vulnerabilities',
  path: '/vulnerabilities',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotRoute = AuthForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anomalies': typeof AnomaliesRoute
  '/assets': typeof AssetsRoute
  '/auth': typeof AuthRouteWithChildren
  '/collaboration': typeof CollaborationRoute
  '/compliance': typeof ComplianceRoute
  '/copilot': typeof CopilotRoute
  '/digital-twin': typeof DigitalTwinRoute
  '/executive': typeof ExecutiveRoute
  '/globe': typeof GlobeRoute
  '/incident-response': typeof IncidentResponseRoute
  '/incidents': typeof IncidentsRoute
  '/investigation': typeof InvestigationRoute
  '/mitre': typeof MitreRoute
  '/network': typeof NetworkRoute
  '/report-gen': typeof ReportGenRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/simulation': typeof SimulationRoute
  '/soc': typeof SocRoute
  '/threat-intel': typeof ThreatIntelRoute
  '/threat-intelligence-ai': typeof ThreatIntelligenceAiRoute
  '/timeline': typeof TimelineRoute
  '/vulnerabilities': typeof VulnerabilitiesRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anomalies': typeof AnomaliesRoute
  '/assets': typeof AssetsRoute
  '/auth': typeof AuthRouteWithChildren
  '/collaboration': typeof CollaborationRoute
  '/compliance': typeof ComplianceRoute
  '/copilot': typeof CopilotRoute
  '/digital-twin': typeof DigitalTwinRoute
  '/executive': typeof ExecutiveRoute
  '/globe': typeof GlobeRoute
  '/incident-response': typeof IncidentResponseRoute
  '/incidents': typeof IncidentsRoute
  '/investigation': typeof InvestigationRoute
  '/mitre': typeof MitreRoute
  '/network': typeof NetworkRoute
  '/report-gen': typeof ReportGenRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/simulation': typeof SimulationRoute
  '/soc': typeof SocRoute
  '/threat-intel': typeof ThreatIntelRoute
  '/threat-intelligence-ai': typeof ThreatIntelligenceAiRoute
  '/timeline': typeof TimelineRoute
  '/vulnerabilities': typeof VulnerabilitiesRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anomalies': typeof AnomaliesRoute
  '/assets': typeof AssetsRoute
  '/auth': typeof AuthRouteWithChildren
  '/collaboration': typeof CollaborationRoute
  '/compliance': typeof ComplianceRoute
  '/copilot': typeof CopilotRoute
  '/digital-twin': typeof DigitalTwinRoute
  '/executive': typeof ExecutiveRoute
  '/globe': typeof GlobeRoute
  '/incident-response': typeof IncidentResponseRoute
  '/incidents': typeof IncidentsRoute
  '/investigation': typeof InvestigationRoute
  '/mitre': typeof MitreRoute
  '/network': typeof NetworkRoute
  '/report-gen': typeof ReportGenRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/simulation': typeof SimulationRoute
  '/soc': typeof SocRoute
  '/threat-intel': typeof ThreatIntelRoute
  '/threat-intelligence-ai': typeof ThreatIntelligenceAiRoute
  '/timeline': typeof TimelineRoute
  '/vulnerabilities': typeof VulnerabilitiesRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anomalies'
    | '/assets'
    | '/auth'
    | '/collaboration'
    | '/compliance'
    | '/copilot'
    | '/digital-twin'
    | '/executive'
    | '/globe'
    | '/incident-response'
    | '/incidents'
    | '/investigation'
    | '/mitre'
    | '/network'
    | '/report-gen'
    | '/reports'
    | '/settings'
    | '/simulation'
    | '/soc'
    | '/threat-intel'
    | '/threat-intelligence-ai'
    | '/timeline'
    | '/vulnerabilities'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/register'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anomalies'
    | '/assets'
    | '/auth'
    | '/collaboration'
    | '/compliance'
    | '/copilot'
    | '/digital-twin'
    | '/executive'
    | '/globe'
    | '/incident-response'
    | '/incidents'
    | '/investigation'
    | '/mitre'
    | '/network'
    | '/report-gen'
    | '/reports'
    | '/settings'
    | '/simulation'
    | '/soc'
    | '/threat-intel'
    | '/threat-intelligence-ai'
    | '/timeline'
    | '/vulnerabilities'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/register'
  id:
    | '__root__'
    | '/'
    | '/anomalies'
    | '/assets'
    | '/auth'
    | '/collaboration'
    | '/compliance'
    | '/copilot'
    | '/digital-twin'
    | '/executive'
    | '/globe'
    | '/incident-response'
    | '/incidents'
    | '/investigation'
    | '/mitre'
    | '/network'
    | '/report-gen'
    | '/reports'
    | '/settings'
    | '/simulation'
    | '/soc'
    | '/threat-intel'
    | '/threat-intelligence-ai'
    | '/timeline'
    | '/vulnerabilities'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/register'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnomaliesRoute: typeof AnomaliesRoute
  AssetsRoute: typeof AssetsRoute
  AuthRoute: typeof AuthRouteWithChildren
  CollaborationRoute: typeof CollaborationRoute
  ComplianceRoute: typeof ComplianceRoute
  CopilotRoute: typeof CopilotRoute
  DigitalTwinRoute: typeof DigitalTwinRoute
  ExecutiveRoute: typeof ExecutiveRoute
  GlobeRoute: typeof GlobeRoute
  IncidentResponseRoute: typeof IncidentResponseRoute
  IncidentsRoute: typeof IncidentsRoute
  InvestigationRoute: typeof InvestigationRoute
  MitreRoute: typeof MitreRoute
  NetworkRoute: typeof NetworkRoute
  ReportGenRoute: typeof ReportGenRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  SimulationRoute: typeof SimulationRoute
  SocRoute: typeof SocRoute
  ThreatIntelRoute: typeof ThreatIntelRoute
  ThreatIntelligenceAiRoute: typeof ThreatIntelligenceAiRoute
  TimelineRoute: typeof TimelineRoute
  VulnerabilitiesRoute: typeof VulnerabilitiesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anomalies': {
      id: '/anomalies'
      path: '/anomalies'
      fullPath: '/anomalies'
      preLoaderRoute: typeof AnomaliesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets': {
      id: '/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collaboration': {
      id: '/collaboration'
      path: '/collaboration'
      fullPath: '/collaboration'
      preLoaderRoute: typeof CollaborationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copilot': {
      id: '/copilot'
      path: '/copilot'
      fullPath: '/copilot'
      preLoaderRoute: typeof CopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digital-twin': {
      id: '/digital-twin'
      path: '/digital-twin'
      fullPath: '/digital-twin'
      preLoaderRoute: typeof DigitalTwinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/executive': {
      id: '/executive'
      path: '/executive'
      fullPath: '/executive'
      preLoaderRoute: typeof ExecutiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/globe': {
      id: '/globe'
      path: '/globe'
      fullPath: '/globe'
      preLoaderRoute: typeof GlobeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incident-response': {
      id: '/incident-response'
      path: '/incident-response'
      fullPath: '/incident-response'
      preLoaderRoute: typeof IncidentResponseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents': {
      id: '/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof IncidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investigation': {
      id: '/investigation'
      path: '/investigation'
      fullPath: '/investigation'
      preLoaderRoute: typeof InvestigationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mitre': {
      id: '/mitre'
      path: '/mitre'
      fullPath: '/mitre'
      preLoaderRoute: typeof MitreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network': {
      id: '/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof NetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report-gen': {
      id: '/report-gen'
      path: '/report-gen'
      fullPath: '/report-gen'
      preLoaderRoute: typeof ReportGenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulation': {
      id: '/simulation'
      path: '/simulation'
      fullPath: '/simulation'
      preLoaderRoute: typeof SimulationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soc': {
      id: '/soc'
      path: '/soc'
      fullPath: '/soc'
      preLoaderRoute: typeof SocRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/threat-intel': {
      id: '/threat-intel'
      path: '/threat-intel'
      fullPath: '/threat-intel'
      preLoaderRoute: typeof ThreatIntelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/threat-intelligence-ai': {
      id: '/threat-intelligence-ai'
      path: '/threat-intelligence-ai'
      fullPath: '/threat-intelligence-ai'
      preLoaderRoute: typeof ThreatIntelligenceAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vulnerabilities': {
      id: '/vulnerabilities'
      path: '/vulnerabilities'
      fullPath: '/vulnerabilities'
      preLoaderRoute: typeof VulnerabilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot': {
      id: '/auth/forgot'
      path: '/forgot'
      fullPath: '/auth/forgot'
      preLoaderRoute: typeof AuthForgotRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthForgotRoute: typeof AuthForgotRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotRoute: AuthForgotRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnomaliesRoute: AnomaliesRoute,
  AssetsRoute: AssetsRoute,
  AuthRoute: AuthRouteWithChildren,
  CollaborationRoute: CollaborationRoute,
  ComplianceRoute: ComplianceRoute,
  CopilotRoute: CopilotRoute,
  DigitalTwinRoute: DigitalTwinRoute,
  ExecutiveRoute: ExecutiveRoute,
  GlobeRoute: GlobeRoute,
  IncidentResponseRoute: IncidentResponseRoute,
  IncidentsRoute: IncidentsRoute,
  InvestigationRoute: InvestigationRoute,
  MitreRoute: MitreRoute,
  NetworkRoute: NetworkRoute,
  ReportGenRoute: ReportGenRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  SimulationRoute: SimulationRoute,
  SocRoute: SocRoute,
  ThreatIntelRoute: ThreatIntelRoute,
  ThreatIntelligenceAiRoute: ThreatIntelligenceAiRoute,
  TimelineRoute: TimelineRoute,
  VulnerabilitiesRoute: VulnerabilitiesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
